#pragma once

#include <string>

namespace choda {

	class Texture
	{

	public:
		Texture();
		Texture(const char* imgPath, const char* type);

	public:
		// returns an id generated by glGenTextures() function
		static unsigned int GenerateFromFile(const char* path);

	public:
		unsigned int id;
		std::string type;
		std::string path;
	};

}


